name: Build & Test
on: [push]
jobs:
  build-all:
    strategy:
      matrix:
        os: 
          - linux
          - darwin
        arch: 
          - amd64
          - arm64
    runs-on: ubuntu-latest
    steps: 
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: "1.22.0"

    - name: Check out Code
      uses: actions/checkout@v4.0.0

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v -ldflags "-X main.Version=${GITHUB_SHA::7}" -o kubectl-browse-pvc .

    - name: Fix permissions
      run: chmod +x ./kubectl-browse-pvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-browse-pvc-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          ./kubectl-browse-pvc
          LICENSE


