name: Release
permissions:
  contents: write
on:
  push:
    tags:
    - "v*.*.*"
jobs:
  build-all:
    strategy:
      matrix:
        os: 
          - linux
          - darwin
        arch: 
          - amd64
          - arm64
    runs-on: ubuntu-latest
    steps: 
    - name: Set up Go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: "1.22.0"

    - name: Check out Code
      uses: actions/checkout@v4.0.0

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v -ldflags "-X main.Version=${{ github.ref_name }}" -o kubectl-browse-pvc .

    - name: Fix permissions
      run: chmod +x ./kubectl-browse-pvc

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kubectl-browse-pvc-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          ./kubectl-browse-pvc
          LICENSE


  # create-release:
  #   runs-on: ubuntu-latest
  #   needs: [build-darwin, build-linux]
  #   steps:
  #   - name: Download Artifacts
  #     uses: actions/download-artifact@v4

  #   - name: ls
  #     run: ls -R

  #   - name: Fix permissions linux
  #     run: chmod +x kubectl-browse-pvc-linux/kubectl-browse-pvc

  #   - name: Fix permissions darwin
  #     run: chmod +x kubectl-browse-pvc-darwin/kubectl-browse-pvc

  #   - name: Zip linux
  #     uses: montudor/action-zip@v1
  #     with:
  #       args: zip -j kubectl-browse-pvc-linux.zip kubectl-browse-pvc-linux/kubectl-browse-pvc kubectl-browse-pvc-linux/LICENSE

  #   - name: Zip darwin
  #     uses: montudor/action-zip@v1
  #     with:
  #       args: zip -j kubectl-browse-pvc-darwin.zip kubectl-browse-pvc-darwin/kubectl-browse-pvc kubectl-browse-pvc-darwin/LICENSE

  #   - name: Create Release
  #     id: create_release
  #     uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "kubectl-browse-pvc-darwin.zip,kubectl-browse-pvc-linux.zip"
  #       artifactErrorsFailBuild: true

  #   - name: Check out Code
  #     uses: actions/checkout@v4.0.0

  #   - name: Update Krew
  #     uses: rajatjindal/krew-release-bot@v0.0.46
